version: "3.9"
services:
    adb2c:
      container_name: "addb2c"
      image: dauh/addb2c:6.2
      build:
        # in my case, Dockerfile was in a subfolder
        context: addb2c
        dockerfile: Dockerfile
      ports:
        - 7192:7192
      environment:
        - ASPNETCORE_URLS=https://+:7192
        - ASPNETCORE_ENVIRONMENT=Development
    addb2csecond:
      container_name: "addb2csecond"
      image: dauh/addb2csecond:1.2
      build:
        # in my case, Dockerfile was in a subfolder
        context: addb2csecond
        dockerfile: Dockerfile
      ports:
        - 7054:7054
      environment:
        - ASPNETCORE_URLS=https://+:7054
        - ASPNETCORE_ENVIRONMENT=Development