version: "3.9"
services:
    adb2c:
      container_name: "addb2c"
      image: dauh/addb2c:6.0
      build:
        # in my case, Dockerfile was in a subfolder
        context: .
        dockerfile: Dockerfile
      ports:
        - 7192:7192
      environment:
        - ASPNETCORE_URLS=https://+:7192
        - ASPNETCORE_ENVIRONMENT=Development